mavenlink/brainstem-js

- spec/brainstem-collection-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
It now calls appropriate method on alls when serializing collection instead of deferring to Backbone method. This allows blacklisting to be applied to entire collections during serialization
> Properly implement Brainstem.Collection#toServerJSON

- spec/brainstem-expectation-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-expectation.coffee
- vendor/assets/javascripts/brainstem/storage-manager.coffee
This PR adds support to mock collection cache object with count when stubbing:
```javascript
expectation = storageManagerInstance.stub('projects', { count: 100 });
collection = new Projects();
collection.fetch();
expectation.respond();
collection.getServerCount();
// 100
```
> Support Brainstem.Collection#getServerCount when expectations are enabled

- spec/brainstem-collection-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
This passes the actual collection instance into the promise callback instead of an array of models. This makes `Collection#fetch` consistent with `Model#fetch`
> Update Collection fetch method so chained callbacks receive collection instance.

- spec/brainstem-model-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-model.coffee
This fixes fields that contain an ISO8601 date along with other characters and converts into NaN.  We now check that the field is ONLY an ISO8601 date and nothing else.
Note: if a field contains ONLY an ISO8601 date, then it will be converted to epoch time.
@jrolfs @cantino
> Fixes date parsing for fields that include an ISO8601 date

- spec/brainstem-collection-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
Currently we return a simple promise, however vanilla Backbone actually returns
the raw value returned from the sync method. The raw value returned from sync is
the promise returned from `$.ajax` which includes the `jqXhr` API as well. This PR
adds the `jqXhr` API to the promise returned from `Brainstem.Collection#fetch` by
passing the `jqXhr` into the final `promise` call. This achieves better API
adherence to Backbone's fetch method and more importantly allows us to abort the
request and access response headers etc.
> Pass jqXhr to promise that Brainstem.Collection#fetch returns

- spec/brainstem-model-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-model.coffee
In mobile, we follow the pattern of serializing forms with hidden attributes for associations. We want Brainstem to ignore fields for associations where those fields are falsey not just null. Here we are not worried about an id of 0.
-- Ben's M
> Don't throw an error when a association id is set to an empty string

- .travis.yml
- spec/brainstem-model-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-model.coffee
Return a [`jqXHR`](http://api.jquery.com/Types/#jqXHR) object wrapped in a jQuery [`promise`](https://api.jquery.com/promise/) just as we do for `Collection#fetch`. This allows the actual request to be aborted and exposes other request information about the native request.
> Return jqXHR wrapped promise from Model#fetch

- spec/loaders/abstract-loader-shared-behavior.coffee
- vendor/assets/javascripts/brainstem/loaders/abstract-loader.coffee
This PR updates `_modelsOrObj` to always return an array, even if `obj` is a single model. This is necessary because of this:
https://github.com/mavenlink/brainstem-js/blob/return_array_from_modelorobj/vendor/assets/javascripts/brainstem/loaders/abstract-loader.coffee#L106
If the `obj` inside of this function is a singular model, then `_getIdsForAssociation` chokes because it tries to pluck `id` from each of the attributes of that model, rather than the id from each model in an array or collection. If `obj` is undefined, we just return an empty array.
@ahuth @jrolfs mind taking a look?
cc @arleigh-atkinson
> Ensure array is returned in all cases in _modelOrObj

- spec/brainstem-collection-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
Pass an instance of the fetched collection to chained `done` callbacks instead of an array of models.
Fixes #72
> Pass collection instance to fetch done callbacks

- spec/brainstem-model-spec.coffee
- spec/storage-manager-spec.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
- vendor/assets/javascripts/brainstem/brainstem-model.coffee
- vendor/assets/javascripts/brainstem/loaders/model-loader.coffee
Fetching a newly instantiated model now results in the new model reference being cached in the storage manager. This allows the reference from instantiation to be used as a canonical reference to the model.
Fixes #71 
Before:
```javascript
var newModel = new Brainstem.Model();
model.fetch().done(function (model) {
console.log(model.attributes);
// fetched attributes
console.log(newModel.attributes);
// {}
console.log(model === newModel);
// false
});
```
After:
```javascript
var newModel = new Brainstem.Model();
model.fetch().done(function (model) {
console.log(model.attributes);
// fetched attributes
console.log(newModel.attributes);
// fetched attributes
console.log(model === newModel);
// true
});
```
> Cache newly fetched model references in storage manager

- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/loaders/collection-loader-spec.coffee
- spec/loaders/model-loader-spec.coffee
- spec/model-spec.coffee
- spec/sync-spec.coffee
- spec/utils-spec.coffee
- src/model.coffee
- src/storage-manager.coffee
Require Underscore and jQuery everwhere. Certain modules were previously relying on Underscore and jQuery from global pollution created by BackboneFactory. Those modules now explicitly require *all* of their dependencies (aka Underscore and jQuery)
> Fix BackboneFactory global pollution

- .travis.yml
- gulpfile.js
- package.json
Since Node 6+ supports everything except for ES6 modules it makes sense to remove the Babel dependency here and simply use CommonJS' `require` instead of `import`.
> Remove Babel dependency from Gulpfile, target NodeJS 6+

- package.json
- spec/storage-manager-spec.coffee
- src/storage-manager.coffee
Ensure collections within the storage manager always have an empty first fetch options object
This ensures pollution cannot happen in case one of these collections is needed (an example would be to avoid initializing a new collection -- such as [brainstem-redux](https://github.com/mavenlink/brainstem-redux))
@naganowl
> Collections have `firstFetchOptions: {}`

- karma.conf.js
- package.json
- spec/singleton-spec.coffee
- spec/singleton-window-spec.coffee
- src/storage-manager.coffee
This is a transitionary bit of code:
- Useful when migrating a codebase from globals to JavaScript modules
- Useful in testing environments which rely on globals
> Add workaround for global singleton

- spec/model-spec.coffee
- src/model.coffee
Only parse timestamps when the attribute has an '_at' in the name or 'date' in the name. 
This is to solve the bug where normal attributes that should be saved as timestamps like this `2017-02-03T16:41:12+00:00` are unintentionally being parsed into integer timestamps. In this example we want to save the original string value and this is not a date field. 
Signed-off-by: Bobby Brown <bobby@mavenlink.com>
https://www.pivotaltracker.com/story/show/139446509
> Parse timestamps only if the attribute has _at or date in the name.

- package.json
- spec/model-spec.coffee
- src/model.coffee
Partially addresses this issue: https://github.com/mavenlink/brainstem-js/issues/76
References to associations aren't cleaned up when a model is destroyed. This PR does this without making any extra requests.
> Cleanup references on destroy

- src/model.coffee
When I cleaned up the source to satisfy our `coffeelint.json` I accidentally removed interpolation from the error output in `Brainstem.Model`.
> Re-add interpolation for error output in Model

- package.json
Seems like `0.4.19` was broken and there isn't anyway to override it.
See https://github.com/npm/npm/issues/10556 for more details.
> Bump to 0.4.20

- lib/brainstem/js/version.rb
- src/model.coffee
- vendor/assets/javascripts/brainstem.js
A bug from bigmaven left a console error of
```
Uncaught Error: Unable to find default_role with id 1231231 in our cached {details.collectionName} collection. We know about 123123, 123123, .... , fragment: pending
```
This PR cleans up that error message to actually output the collection name.
Compiled with `gulp build-gem`
> Fix the error message to include the collection name

- spec/expectation-spec.coffee
- src/expectation.coffee
Added `cacheKey` and `optionalFields` to the expectation optionTypes to be compared against for collections.
> Update expectation to check for more optionTypes

- package.json
- spec/storage-manager-spec.coffee
- src/storage-manager.coffee
Backgrid integrations in breaking because they assume the cache always exists. This is a bad integration since the UI should not care about the cache whatsoever. Alas, we have to revert to preserve existing features. If we want to improve the cache invalidation logic, we will want to remove any access to the cache first (which will identify these issues). And then bust the cache whenever we feel like it.
**Summary**
No.
Backgrid paginator code in our Collection class is broken when the cache is busted. The cache should really be private and only used by the storage manager. :( 
**Test plan**
> Revert cache invalidation logic

- gulpfile.js
- package.json
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/sync-spec.coffee
- src/loaders/abstract-loader.coffee
- src/sync.coffee
**Summary**
This is a minimally impacting feature. It is backwards compatible since it does not affect any existing feature.
This is useful when collecting data on server requests. For example, my use case is analytics. I want to see the performance of my features. Each model or collection fetch can always be associated with some feature. Seeing the usage and performance of such fetches is useful!
**Test plan**
Unit test implemented which calls the `beforeSend` option passed into sync. The `jqXhr` object does not expose the internal headers. I will also build this against the bigmaven application.
> Custom XHR header: X-Feature-Name

- package.json
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/sync-spec.coffee
- src/loaders/abstract-loader.coffee
- src/sync.coffee
**Summary**
No.
Follow-up to https://github.com/mavenlink/brainstem-js/pull/126
Looks like `feature_name` can sometimes be an actual filter name. This tries to avoid clobbering filter names by nesting in a namespace.
**Test plan**
> Nest custom headers in `headers` key

- package.json
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/utils-spec.coffee
- src/loaders/abstract-loader.coffee
- src/utils.coffee
Related to https://www.pivotaltracker.com/story/show/158237926, corresponds to https://github.com/mavenlink/mavenlink/pull/13016
Associated records can be loaded via the "only" param in the URL. When there are many associated records, this can go over the URL limit (which is around 2000 characters or so).
We cannot detect what the actual length of our URL will be, because there are filters and custom subdomains involved as well. Instead, we use a heuristic of allowing 150 ids.
We got there by:
(2000 max URL limit - 500 max filters length - 100 max subdomain length) / 11 max id length (including comma) == about 150-ish
All of the "max" values above are assumed to be "reasonable" limits.
> Load associated records in chunks if necessary

- spec/model-spec.coffee
- src/model.coffee
**Summary**
This fixes an issue where the string could just contain a Z and be considered a valid iso8601 timestamp. 
**Test plan**
We added tests that ensured strings with a z would not always be considered valid, they must have the rest of the regex matching.
> Fix incorrect regex where the string could just contain a Z and pass

- spec/collection-spec.coffee
- spec/loaders/collection-loader-spec.coffee
- src/collection.coffee
- src/expectation.coffee
- src/loaders/collection-loader.coffee
**Summary**
Sometimes we have large collections that we don't to `trigger('add' ....)` on each one for performance reasons
**Test plan**
Everything should be well encapsulated by the specs, and all the changes are opt in so it should not cause any breaking changes.
> Allow passing silent option to backbone Collection#add

- spec/model-spec.coffee
- src/model.coffee
**Summary**
There are some instances where bad data as is loaded into the collection of ids. If those instances of null or undefined they should noop.
**Test plan**
This is tested in the specs
> feat: Get operation ignores null or undefined as attribute ids

- package.json
- yarn.lock
- Bump `underscore` from 1.12.1 to 1.13.6. The [changelog](https://underscorejs.org/#changelog) lists no breaking changes.
> Bump underscore from 1.12.1 to 1.13.6

- package.json
- yarn.lock
- Upgrade dev dependency `browserify` from 13.0.0 to 17.0.0. 
- The [changelog](https://github.com/browserify/browserify/blob/master/changelog.markdown) lists dependency updates as the major changes, along with breaking support for IE8-10, which we do not intend to support.
> Upgrade browserify from 13.0.0 to 17.0.0

- package.json
- yarn.lock
- Upgrade watchify from 3.9.0 to 4.0.0
- [Changelog](https://github.com/browserify/watchify/releases) lists no breaking changes except deprecation of older node versions.
> Upgrade watchify from 3.9.0 to 4.0.0

- package.json
- yarn.lock
- Bump browserify-shim from 3.8.14 to 3.8.16
- The diffs are mainly dependency and security updates. (See https://github.com/thlorenz/browserify-shim/compare/v3.8.14...v3.8.15 and https://github.com/thlorenz/browserify-shim/compare/v3.8.15...v3.8.16.)
> Bump browserify-shim from 3.8.14 to 3.8.16

- package.json
- yarn.lock
- Bump karma from 4.4.1 to 6.4.3
- The [breaking changes](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md) in 5.0 and 6.0 do not affect us.
> Bump karma from 4.4.1 to 6.4.3

- .github/workflows/test.yml
Use checkout v3 instead of v2. We cannot upgrade to v4 because we are not on node 20.
> Use checkout v3 instead of v2

- gulpfile.js
Fix Karma deprecation warning:
```
06 03 2024 09:04:09.491:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
```
> Fix karma server deprecation

- karma.conf.js
Silence karma filetype warnings:
```
06 03 2024 12:16:10.041:WARN [middleware:karma]: Unable to determine file type from the file extension, defaulting to js.
To silence the warning specify a valid type for /Users/georgewang/workspace/brainstem-js/spec/utils-spec.coffee in the configuration file.
See https://karma-runner.github.io/latest/config/files.html
```
> Silence karma filetype warnings

- package.json
- yarn.lock
Bump karma sourcemap loader to 0.4.0. No breaking changes mentioned in the [changelog](https://github.com/demerzel3/karma-sourcemap-loader/blob/master/CHANGELOG.md).
> Bump karma sourcemap loader

- package.json
- yarn.lock
> Update package.json to correct version of jasmine jquery matchers

- spec/helpers/builders.coffee
- src/loaders/collection-loader.coffee
- src/storage-manager.coffee
Although `Object.assign` and `$.extend` have some differences (https://stackoverflow.com/questions/38345937/object-assign-vs-extend), the should not apply to us, as 1) we do not use the `deep: true` option in these methods, and 2) we are always merging in an empty object (`{}`), so it should never be undefined.
> Prefer Object.assign to $.extend to merge objects

- package.json
- spec/helpers/spec-helper.coffee
- src/loaders/collection-loader.coffee
- yarn.lock
Brainstem has one instance of `$.extend` with the `deep: true` option, so replace it with `lodash.merge` to preserve deep merging behavior.
One remaining example of `$.extend` was also replaced with `lodash.merge` to avoid creating new objects in the response.
I decided to use a package instead of writing our own implementation to hopefully avoid subtle bugs with deep merging, handling undefined values, etc.
> Remove jquery extend deep with lodash merge

- package.json
The latest version of ubuntu focal runs node 18.17, so let's allow any version of node 18 until we can upgrade.
> Allow any version of node 18 to allow ubuntu focal in builds

- package.json
- yarn.lock
Address this CVE: https://github.com/mavenlink/brainstem-js/security/dependabot/10
> Add resolution for merge package to fix cve

- spec/helpers/builders.coffee
- src/storage-manager.coffee
Reverts mavenlink/brainstem-js#209 because bigmaven is showing test errors when using the latter
> Revert "Prefer Object.assign to $.extend to merge objects"

- yarn.lock
Resolves https://github.com/mavenlink/brainstem-js/security/dependabot/62, https://github.com/mavenlink/brainstem-js/security/dependabot/61, and https://github.com/mavenlink/brainstem-js/security/dependabot/60
> Bump elliptic from 6.5.4 to 6.5.7

- gulpfile.js
- package.json
- yarn.lock
Remove deprecated `gulp-util` as per https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> Remove direct dependency on gulp-util

- yarn.lock
Resolves https://github.com/mavenlink/brainstem-js/security/dependabot/59 and https://github.com/mavenlink/brainstem-js/security/dependabot/65
> Bump socket.io from 4.7.4 to 4.8.0

- yarn.lock
Addresses https://github.com/mavenlink/brainstem-js/security/dependabot/59. The [diff](https://github.com/socketio/socket.io/blob/main/packages/socket.io-adapter/CHANGELOG.md#255-2024-06-18) only contains a security patch.
> Bump `socket.io-adapter` from 2.5.4 to 2.5.5
