mavenlink/brainstem-js

- spec/loaders/abstract-loader-shared-behavior.coffee
- vendor/assets/javascripts/brainstem/loaders/abstract-loader.coffee
> Nested include statements respect the original request's cache setting

- spec/loaders/abstract-loader-shared-behavior.coffee
- vendor/assets/javascripts/brainstem/brainstem-collection.coffee
- vendor/assets/javascripts/brainstem/brainstem-model.coffee
- vendor/assets/javascripts/brainstem/loaders/abstract-loader.coffee
> Optional fields

- Gemfile.lock
- spec/storage-manager-spec.coffee
- vendor/assets/javascripts/brainstem/storage-manager.coffee
TODO
-
@cantino @rogerneel 
@jrolfs
> Storage manager can bootstrap data without an ajax call

- .travis.yml
- lib/brainstem/js/version.rb
- package.json
- spec/collection-spec.coffee
- spec/helpers/spec-helper.coffee
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/loaders/collection-loader-spec.coffee
- spec/loaders/model-loader-spec.coffee
- spec/model-spec.coffee
- spec/storage-manager-spec.coffee
- spec/utils-spec.coffee
- src/collection.coffee
- src/loaders/abstract-loader.coffee
- src/loaders/model-loader.coffee
- src/model.coffee
- src/storage-manager.coffee
- src/sync.coffee
- src/utils.coffee
- vendor/assets/javascripts/brainstem.js
For compatibility with applications using Marionette 1.x
> Downgrade backbone

- karma.conf.js
- package.json
> Add sourcemap support to karma config

- gulpfile.babel.js
- src/collection.coffee
- src/loaders/abstract-loader.coffee
- src/model.coffee
- src/storage-manager.coffee
- src/sync.coffee
- src/utils.coffee
- Fail on CI for CoffeeLint warnings
> Fail on CoffeeLint warnings

- package.json
Use a non-alpha version once https://github.com/mavenlink/mavenlink-js/pull/334 is good to go.
> Bump version of package

- brainstemjs.gemspec
- Remove now extraneous `executables` and `test_files` properties from spec
- Consistent comments and quoting 😬
> Clean up and remove unnecessary properties from gemspec

- package.json
- spec/model-spec.coffee
- src/model.coffee
With the useWhitelist flag, the blacklist for models will be generated from the difference between attributes and `create_whitelist` or `update_whitelist` attribute.
@juanca We would appreciate a review here! Thanks!
> useWhitelist flag to create blacklist based on whitelist of controller

- .gitignore
- README.md
- karma.conf.js
- package.json
- spec/collection-spec.coffee
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/storage-manager-spec.coffee
- src/storage-manager.coffee
- yarn.lock
> Straight-forward cache invalidation

- package.json
- src/constants.coffee
- src/loaders/collection-loader.coffee
- src/model.coffee
Corresponding PR to:
- https://github.com/mavenlink/rfc/pull/28
- https://github.com/mavenlink/brainstem/pull/100
> Support pagination keys in API responses

- README.md
Adding steps for how-to publish. Running these steps with @brentgaither
> Publishing steps

- package.json
- spec/collection-spec.coffee
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/model-spec.coffee
- src/collection.coffee
- src/loaders/abstract-loader.coffee
- src/model.coffee
**Summary**
Update black and white list to block and allow list
**Test plan**
> Switch black and white list to block and allow list

- package.json
- spec/collection-spec.coffee
- spec/loaders/abstract-loader-shared-behavior.coffee
- spec/model-spec.coffee
- src/collection.coffee
- src/loaders/abstract-loader.coffee
- src/model.coffee
Reverts mavenlink/brainstem-js#143
> Revert "Switch black and white list to block and allow list"

- package.json
- yarn.lock
- This PR adds `yarn deduplicate` to make it easier to manage packages. 
- I also ran the script to clean up unused packages.
> Add and run yarn deduplicate

- .github/workflows/test.yml
- package.json
Upgrade node from 14 to 18.19.0 to match bigmaven.
> Upgrade node to 18.19.0

- package.json
- yarn.lock
Upgrade inflection from 1.8.0 to 3.0.0
> Upgrade inflection from 1.8.0 to 3.0.0

- package.json
- yarn.lock
Update package.json to reflect actual minimist version
> Update package.json to reflect actual minimist version

- package.json
- yarn.lock
- Bump karma browserify from 5.3.0 to 8.1.0
> Bump karma browserify from 5.3.0 to 8.1.0

- package.json
- Update the brainstem version from 0.7.3 to 0.8.0.
- This release contains dependency updates and is a minor version change because of the upgrade to node 18.
> Update version from 0.7.3 to 0.8.0

- yarn.lock
Run `yarn deduplicate` after dependabot updates.
> package.json cleanup

- package.json
Update `brainstem-js` to 0.8.1 to publish dependency updates.
> v0.8.1 bump

- package.json
- yarn.lock
Bump karma spec reporter to 0.0.36
> Bump karma spec reporter

- spec/helpers/spec-helper.coffee
Prefer native DOM manipulation methods to jquery methods.
> Remove jquery DOM manipulation

- package.json
- spec/helpers/spec-helper.coffee
- src/loaders/collection-loader.coffee
- yarn.lock
Reverts mavenlink/brainstem-js#210
> Revert "Remove jquery extend deep with lodash merge"

- package.json
This version locks in some security patches / dependency updates and removes underscore wrapping because of issues it causes in downstream packages.
> Bump version to 0.9.1
